#include <stdio.h>
#include <unistd.h>
#include <net/if.h> // Required for if_nametoindex()
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include "ips.skel.h" // The skeleton header generated by bpftool
#include <arpa/inet.h>
#include <bpf/bpf.h>
#include <time.h>
#include <sys/stat.h>
#include <errno.h>

#include "ips_fast_common.h"

//------------------------------- Functions -----------------------------------------------------
void load_blocklist_from_csv(int blocklist_fd) {
    FILE *fp = fopen(CSV_FILE, "r");
    if (!fp) {
        printf("[i] No existing blocklist.csv found. Starting fresh.\n");
        return;
    }

    char line[256];
    int count = 0;

    // Read the CSV line by line (Format: IP,Timestamp,IsStatic)
    while (fgets(line, sizeof(line), fp)) {
        char ip_str[32];
        uint64_t ts;
        int is_static;

        if (sscanf(line, "%31[^,],%lu,%d", ip_str, &ts, &is_static) == 3) {
            struct in_addr addr;
            inet_aton(ip_str, &addr); // Convert string to IP integer

            __u32 key = addr.s_addr;
            struct ips_blocklist_data val = { .ban_timestamp = ts, .is_static = is_static };

            // Push it down into the eBPF kernel map
            bpf_map_update_elem(blocklist_fd, &key, &val, BPF_ANY);
            count++;
        }
    }
    fclose(fp);
    printf("[i] Loaded %d bans from %s\n", count, CSV_FILE);
}

// Saves RAM to Disk whenever a change happens
void save_blocklist_to_csv(int blocklist_fd) {
    FILE *fp = fopen(CSV_TEMP, "w");
    if (!fp) {
        fprintf(stderr, "[!] Failed to open temp CSV for writing.\n");
        return;
    }

    // Allocate arrays in user-space to catch the massive data dump
    __u32 keys[BATCH_SIZE];
    struct ips_blocklist_data values[BATCH_SIZE];

    // Batching state variables
    __u32 batch_token;
    void *in_batch = NULL;          // NULL tells the kernel "Start from the beginning"
    void *out_batch = &batch_token; // The kernel will write the "bookmark" here
    __u32 count;
    int err = 0;

    // The Batch Loop
    while (1) {
        count = BATCH_SIZE; //tell the kernel max capacity

        err = bpf_map_lookup_batch(blocklist_fd, in_batch, out_batch, keys, values, &count, NULL);

        // Process items the kernel gave us
        for (__u32 i = 0; i < count; i++) {
            struct in_addr addr;
            addr.s_addr = keys[i];


            fprintf(fp, "%s,%llu,%llu\n",
                    inet_ntoa(addr),
                    (unsigned long long)values[i].ban_timestamp,
                    (unsigned long long)values[i].is_static);
        }

        // err == 0 means the batch is full, and there is more data waiting.
        // err == ENOENT means we successfully reached the absolute end of the map.
        if (err != 0) {
            break;
        }

        // Pass the bookmark back into the kernel for the next loop
        in_batch = &batch_token;
    }

    fclose(fp);
    rename(CSV_TEMP, CSV_FILE); // Atomic swap
}

//------------------------------------------------------------------------------------------------------------
// Ring Buffer Callback
//------------------------------------------------------------------------------------------------------------
int handle_ban_event(void *ctx, void *data, size_t data_sz) {
    int blocklist_fd = *(int *)ctx;
    const struct ips_ban_event *event = data;

    struct in_addr ip_addr;
    ip_addr.s_addr = event->src_ip;

    printf("[!] FLOOD DETECTED: %s banned! Drops: %d\n", inet_ntoa(ip_addr), event->drop_count);

    // BPF already blocked it to stop traffic instantly, but we need to assign the real timestamp
    struct ips_blocklist_data block_data;
    block_data.ban_timestamp = (uint64_t)time(NULL);
    block_data.is_static = 0;

    bpf_map_update_elem(blocklist_fd, &event->src_ip, &block_data, BPF_ANY);

    // Save to disk so it persists across reboots
    save_blocklist_to_csv(blocklist_fd);
    printf("[i] Blocklist saved to disk.\n");

    return 0;
}

//------------------------------------------------------------------------------------------------------------


int main(int argc, char **argv) {
    //Disable output buffering so printf shows up immediately in CLion
    setbuf(stdout, NULL);
    
    int err;
    
    // Tell the kernel to allow our 65,000-entry maps to allocate RAM.
    struct rlimit rlim = {
        .rlim_cur = RLIM_INFINITY,
        .rlim_max = RLIM_INFINITY,
    };
    if (setrlimit(RLIMIT_MEMLOCK, &rlim)) {
        fprintf(stderr, "[!] Failed to increase RLIMIT_MEMLOCK!\n");
        return 1;
    }

    // 3. Open and load the eBPF program into the kernel
    struct ips_bpf *skel = ips_bpf__open_and_load();
    if (!skel) {
        // If this prints, it means the kernel actively rejected our eBPF code
        fprintf(stderr, "[!] FATAL: Failed to open and load BPF skeleton.\n");
        return 1; 
    }    
    
    // ----------------------------------------------------------------
    // AUTO-DETECT NETWORK INTERFACE & ATTACH
    // ----------------------------------------------------------------
    int ifindex = 0;
    const char *iface_name = NULL;

    // Try native Linux interface
    if ((ifindex = if_nametoindex("enp2s0")) > 0) {
        iface_name = "enp2s0";
    }
    // Try Oracle VM interface
    else if ((ifindex = if_nametoindex("enp0s3")) > 0) {
        iface_name = "enp0s3";
    }

    if (ifindex <= 0) {
        fprintf(stderr, "[!] Error: No known network interfaces found!\n");
        return 1;
    }

    printf("[i] Using interface %s (Index: %d)\n", iface_name, ifindex);

    // Attach the XDP program to the detected interface
    struct bpf_link *link = bpf_program__attach_xdp(skel->progs.fast_path_parser, ifindex);
    if (!link) {
        fprintf(stderr, "[!] Failed to attach XDP program to %s\n", iface_name);
        return 1;
    }

    printf("IPS Fast-Path successfully attached to %s!\n", iface_name);
    printf("XDP is active. Listening for traffic...\n");
    printf("(Press Ctrl+C or use CLion's Stop button to exit)\n");

    // 5. Keep the user-space program alive so the XDP hook remains attached
    printf("IPS Fast-Path successfully attached to %s!\n", iface_name);
    printf("Monitoring traffic... Press Ctrl+C to stop.\n\n");

    //Get File Descriptors (FDs)
    int tracker_fd = bpf_map__fd(skel->maps.ip_tracker);
    int blocklist_fd = bpf_map__fd(skel->maps.blocklist);
    int allowlist_fd = bpf_map__fd(skel->maps.allowlist);
    int honeypot_fd = bpf_map__fd(skel->maps.honeypot_map);

    // --- INITIALIZE STORAGE DIRECTORY ---
    // 0755 means: Owner can read/write/execute. Others can read/execute.
    if (mkdir(IPS_SAVE_DIR, 0755) == 0) {
        printf("[i] Created new storage directory at %s\n", IPS_SAVE_DIR);
    }

    // --- LOAD SAVED DATA ---
    load_blocklist_from_csv(blocklist_fd);

    // --- SETUP RING BUFFER ---
    struct ring_buffer *rb = NULL;
    rb = ring_buffer__new(bpf_map__fd(skel->maps.ban_events), handle_ban_event, &blocklist_fd, NULL);
    if (!rb) {
        fprintf(stderr, "[!] Failed to create ring buffer\n");
        return 1;
    }

    printf("--- System Status: Event-Driven Mode Active ---\n");

    while (1) {
        // Wait for ban events from the kernel for up to 1 second
        // If an attack happens, this wakes up instantly (0ms latency).
        // If nothing happens, it loops every 1 second to run the aging logic.
        int err = ring_buffer__poll(rb, 1000);
        if (err < 0) {
            fprintf(stderr, "[!] Error polling ring buffer: %d\n", err);
            break;
        }

        bool map_changed = 0;

        // ====================================================================
        // AGING (Blocklist Eviction)
        // ====================================================================

        __u32 bl_key = 0, bl_next_key;
        struct ips_blocklist_data bl_value;
        uint64_t current_time = (uint64_t)time(NULL);

        while (bpf_map_get_next_key(blocklist_fd, &bl_key, &bl_next_key) == 0) {

            bpf_map_lookup_elem(blocklist_fd, &bl_next_key, &bl_value);

            // We ONLY age out dynamic bans (is_static == 0)
            if (bl_value.is_static == 0) {
                if ((current_time - bl_value.ban_timestamp) > AGING_THRESHOLD) {

                    struct in_addr unban_ip;
                    unban_ip.s_addr = bl_next_key;

                    //Remove them from the eBPF blocklist.
                    bpf_map_delete_elem(blocklist_fd, &bl_next_key);
                    printf("[i] AGING: IP %s has served its time. Unbanned.\n", inet_ntoa(unban_ip));

                    map_changed = 1; //flag for change of map
                }
            }
            bl_key = bl_next_key;
        }

        if (map_changed) {
            save_blocklist_to_csv(blocklist_fd);
            printf("[i] Blocklist saved to disk.\n");
        }
    }

    // 6. Cleanup (This runs when you stop the program)
    ring_buffer__free(rb);
    bpf_link__destroy(link);
    ips_bpf__destroy(skel);
    return 0;
}

//
// Created by raul on 7/7/26.
//
