#include <stdio.h>
#include <unistd.h>
#include <net/if.h> // Required for if_nametoindex()
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include "ips.skel.h" // The skeleton header generated by bpftool
#include <arpa/inet.h>
#include <bpf/bpf.h>
#include <time.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>

#include "ips_fast_common.h"

//------------------------------- Functions -----------------------------------------------------

void load_config(const char *filename, struct ips_config *config) {
    // SET DEFAULTS
    config->ban_duration_sec = 3600;
    config->token_bucket_max = 50;
    config->token_refill_rate = 10;
    config->max_tolerated_drops = 15;

    // OPEN THE FILE
    FILE *file = fopen(filename, "r");
    if (!file) {
        fprintf(stderr, "[*] /config/config.ini not found. Using safe defaults.\n");
        return;
    }

    char line[256];
    char key[128], value[128];

    // READ LINE-BY-LINE
    while (fgets(line, sizeof(line), file)) {

        // Skip comments
        if (line[0] == '#' || line[0] == ';' || line[0] == '\n') {
            continue;
        }

        // EXTRACT KEY AND VALUE

        if (sscanf(line, " %127[^= ] = %127s", key, value) == 2) {

            // MAP STRINGS TO STRUCT VARIABLES
            if (strcmp(key, "ban_duration_seconds") == 0) {
                config->ban_duration_sec = atoi(value); // atoi converts string to int
            }
            else if (strcmp(key, "token_bucket_max") == 0) {
                if (atoi(value)==0) {
                    printf("[!] config.ini is not valid. Max bucket tokens can not be 0. (Minimum is 1)");
                    return;
                }
                config->token_bucket_max = atoi(value); //debatable if it is worth to switch to strtol for its error detection
            }
            else if (strcmp(key, "token_refill_rate") == 0) {
                config->token_refill_rate = atoi(value);
            }
            else if (strcmp(key, "max_tolerated_drops") == 0) {
                config->max_tolerated_drops = atoi(value);
            }
        }
    }

    fclose(file);
    printf("[+] Configuration loaded successfully.\n");
}

void load_blocklist_from_csv(int blocklist_fd) {
    FILE *fp = fopen(CSV_FILE, "r");
    if (!fp) {
        printf("[i] No existing blocklist.csv found. Starting fresh.\n");
        return;
    }

    char line[256];
    int count = 0;

    // Read the CSV line by line (Format: IP,Prefixlen,Timestamp,IsStatic).
    // Prefixlen carries CIDR ranges (e.g. threat-intel subnets) through restarts;
    // single-IP dynamic bans are just the /32 case of the same format.
    while (fgets(line, sizeof(line), fp)) {
        char ip_str[32];
        unsigned int prefixlen;
        uint64_t ts;
        int is_static;

        if (sscanf(line, "%31[^,],%u,%lu,%d", ip_str, &prefixlen, &ts, &is_static) == 4) {
            struct in_addr addr;
            inet_aton(ip_str, &addr); // Convert string to IP integer

            struct lpm_ip_key key = { .prefixlen = prefixlen, .ip = addr.s_addr };
            struct ips_blocklist_data val = { .ban_timestamp = ts, .is_static = is_static };

            // Push it down into the eBPF kernel map
            bpf_map_update_elem(blocklist_fd, &key, &val, BPF_ANY);
            count++;
        }
    }
    fclose(fp);
    printf("[i] Loaded %d bans from %s\n", count, CSV_FILE);
}

// ------------------------------------------------------------------------------------------------------------
// Generic batched map -> CSV dump. Saves RAM to Disk whenever a change happens.
// `fmt` renders one key/value pair; `key_size`/`value_size` are that map's key/value type
// sizes, used to stride through the raw batch buffers since both differ per map (e.g. the
// blocklist's LPM_TRIE key is a struct lpm_ip_key, not a bare __u32 like the other maps).
// ------------------------------------------------------------------------------------------------------------
typedef void (*csv_formatter_fn)(FILE *fp, const void *key, const void *value);

static void fmt_blocklist_row(FILE *fp, const void *key, const void *value) {
    const struct lpm_ip_key *k = key;
    const struct ips_blocklist_data *v = value;
    struct in_addr addr = { .s_addr = k->ip };
    fprintf(fp, "%s,%u,%llu,%llu\n", inet_ntoa(addr), k->prefixlen,
            (unsigned long long)v->ban_timestamp,
            (unsigned long long)v->is_static);
}

static void fmt_tracker_row(FILE *fp, const void *key, const void *value) {
    const __u32 *k = key;
    const struct ips_token_bucket *v = value;
    struct in_addr addr = { .s_addr = *k };
    fprintf(fp, "%s,%llu,%u,%u\n", inet_ntoa(addr),
            (unsigned long long)v->last_update, v->tokens, v->drop_count);
}

static void fmt_flag_row(FILE *fp, const void *key, const void *value) {
    const __u32 *k = key;
    const __u8 *v = value;
    struct in_addr addr = { .s_addr = *k };
    fprintf(fp, "%s,%u\n", inet_ntoa(addr), *v);
}

void save_batch_map_to_csv(int fd, const char *temp_file, const char *final_file,
                            size_t key_size, size_t value_size, csv_formatter_fn fmt) {
    FILE *fp = fopen(temp_file, "w");
    if (!fp) {
        fprintf(stderr, "[!] Failed to open temp CSV for writing: %s\n", temp_file);
        return;
    }

    // Allocate arrays in user-space to catch the massive data dump
    void *keys = malloc((size_t)BATCH_SIZE * key_size);
    void *values = malloc((size_t)BATCH_SIZE * value_size);
    if (!keys || !values) {
        free(keys);
        free(values);
        fclose(fp);
        return;
    }

    // Batching state variables
    __u32 batch_token;
    void *in_batch = NULL;          // NULL tells the kernel "Start from the beginning"
    void *out_batch = &batch_token; // The kernel will write the "bookmark" here
    __u32 count;
    int err = 0;

    // The Batch Loop
    while (1) {
        count = BATCH_SIZE; //tell the kernel max capacity

        err = bpf_map_lookup_batch(fd, in_batch, out_batch, keys, values, &count, NULL);

        // Process items the kernel gave us
        for (__u32 i = 0; i < count; i++) {
            fmt(fp, (const __u8 *)keys + (size_t)i * key_size,
                    (const __u8 *)values + (size_t)i * value_size);
        }

        // err == 0 means the batch is full, and there is more data waiting.
        // err == ENOENT means we successfully reached the absolute end of the map.
        if (err != 0) {
            break;
        }

        // Pass the bookmark back into the kernel for the next loop
        in_batch = &batch_token;
    }

    free(keys);
    free(values);
    fclose(fp);
    rename(temp_file, final_file); // Atomic swap
}

void save_blocklist_to_csv(int blocklist_fd) {
    save_batch_map_to_csv(blocklist_fd, CSV_TEMP, CSV_FILE,
                           sizeof(struct lpm_ip_key), sizeof(struct ips_blocklist_data), fmt_blocklist_row);
}

void save_tracker_to_csv(int tracker_fd) {
    save_batch_map_to_csv(tracker_fd, TRACKER_CSV_TEMP, TRACKER_CSV_FILE,
                           sizeof(__u32), sizeof(struct ips_token_bucket), fmt_tracker_row);
}

void save_simple_map_to_csv(int fd, const char *temp_file, const char *final_file) {
    save_batch_map_to_csv(fd, temp_file, final_file, sizeof(__u32), sizeof(__u8), fmt_flag_row);
}

// A new ban only ever adds one entry, so persisting it doesn't need to read the whole
// map back and rewrite the whole file (O(n) per ban -> O(n^2) for n bans in a burst).
// Just append the one line. The eBPF map stays the source of truth; save_blocklist_to_csv()
// (driven by aging, when a ban expires) still does the full rewrite, which reconciles/
// compacts the file since removing a line from a flat file can't be done incrementally.
static void append_blocklist_entry_to_csv(struct lpm_ip_key key, const struct ips_blocklist_data *block_data) {
    FILE *fp = fopen(CSV_FILE, "a");
    if (!fp) {
        fprintf(stderr, "[!] Failed to open %s for appending.\n", CSV_FILE);
        return;
    }
    fmt_blocklist_row(fp, &key, block_data);
    fclose(fp);
}

//------------------------------------------------------------------------------------------------------------
// Ring Buffer Callback
//------------------------------------------------------------------------------------------------------------

static const char *ban_reason_to_str(__u32 reason) {
    switch (reason) {
        case IPS_BAN_REASON_RATE_LIMIT: return "rate limit exceeded";
        default: return "unknown reason";
    }
}

int handle_ban_event(void *ctx, void *data, size_t data_sz) {
    int blocklist_fd = *(int *)ctx;
    const struct ips_ban_event *event = data;

    struct in_addr ip_addr;
    ip_addr.s_addr = event->src_ip;

    printf("[!] BAN: %s (%s) Drops: %u\n",
           inet_ntoa(ip_addr), ban_reason_to_str(event->reason), event->drop_count);

    // Format the key for the LPM Trie (Single IP = /32)
    struct lpm_ip_key ban_key;
    ban_key.prefixlen = 32;
    ban_key.ip = event->src_ip;

    // Prepare the real-time data
    struct ips_blocklist_data block_data;
    block_data.ban_timestamp = (uint64_t)time(NULL);
    block_data.is_static = 0;

    //Update the kernel map using the new LPM key
    bpf_map_update_elem(blocklist_fd, &ban_key, &block_data, BPF_ANY);

    // O(1) append instead of an O(n) full blocklist dump
    append_blocklist_entry_to_csv(ban_key, &block_data);
    printf("[i] Ban appended to disk.\n");

    return 0;
}

//------------------------------------------------------------------------------------------------------------


int main(int argc, char **argv) {
    // Disable output buffering so printf shows up immediately in CLion
    setbuf(stdout, NULL);

    struct ips_config current_config;
    int err; //error variable initialization
    // Load the settings
    load_config(CONFIG_FILE_PATH, &current_config);

    //
    printf("Starting IPS with: \n");
    printf("Ban Duration: %u seconds\n", current_config.ban_duration_sec);
    printf("Max Tolerated Drops: %u drops\n", current_config.max_tolerated_drops);
    printf("Bucket size: %u tokens\n", current_config.token_bucket_max);
    printf("Token Refill Rate: %u tokens/sec \n", current_config.token_refill_rate);
    
    // Tell the kernel to allow our maps to allocate RAM.
    struct rlimit rlim = {
        .rlim_cur = RLIM_INFINITY,
        .rlim_max = RLIM_INFINITY,
    };
    if (setrlimit(RLIMIT_MEMLOCK, &rlim)) {
        fprintf(stderr, "[!] Failed to increase RLIMIT_MEMLOCK!\n");
        return 1;
    }

    // Open the eBPF program without loading it into the kernel yet
    struct ips_bpf *skel = ips_bpf__open();
    if (!skel) {
        fprintf(stderr, "[!] FATAL: Failed to open BPF skeleton.\n");
        return 1;
    }

    // INJECT CONFIG INTO THE KERNEL via .rodata
    skel->rodata->burst_tokens = current_config.token_bucket_max;
    skel->rodata->max_tolerated_drops = current_config.max_tolerated_drops;
    // Calculate the refill interval in nanoseconds (1 second = 1,000,000,000 ns)
    if (current_config.token_refill_rate > 0) {
        skel->rodata->refill_interval_ns = 1000000000ULL / current_config.token_refill_rate;
    } else {
        skel->rodata->refill_interval_ns = 1000000000ULL; // Fallback to 1 PPS
    }

    // Now load the program into the kernel with our injected configuration
    err = ips_bpf__load(skel);
    if (err) {
        fprintf(stderr, "[!] FATAL: Failed to load BPF skeleton.\n");
        ips_bpf__destroy(skel);
        return 1;
    }    

    // BPF filesystem define

    const char *pin_path = "/sys/fs/bpf/ips_blocklist";

    bpf_map__unpin(skel->maps.blocklist, pin_path); //unpin in case we had a crash and it remained unpinned

    err = bpf_map__pin(skel->maps.blocklist, pin_path);
    if (err) {
        fprintf(stderr, "[!] FATAL: Failed to pin blocklist map: %d.\n", err);
        return 1;
    }

    fprintf(stderr, "[+] Pin blocklist map pinned to %s.\n", pin_path);

    // ----------------------------------------------------------------
    // AUTO-DETECT NETWORK INTERFACE & ATTACH
    // ----------------------------------------------------------------
    int ifindex = 0;
    const char *iface_name = NULL;

    // Try native Linux interface
    if ((ifindex = if_nametoindex("enp2s0")) > 0) {
        iface_name = "enp2s0";
    }
    // Try Oracle VM interface
    else if ((ifindex = if_nametoindex("enp0s3")) > 0) {
        iface_name = "enp0s3";
    }

    if (ifindex <= 0) {
        fprintf(stderr, "[!] Error: No known network interfaces found!\n");
        return 1;
    }

    printf("[i] Using interface %s (Index: %d)\n", iface_name, ifindex);

    // Attach the XDP program to the detected interface
    struct bpf_link *link = bpf_program__attach_xdp(skel->progs.fast_path_parser, ifindex);
    if (!link) {
        fprintf(stderr, "[!] Failed to attach XDP program to %s\n", iface_name);
        return 1;
    }

    printf("IPS Fast-Path successfully attached to %s!\n", iface_name);
    printf("XDP is active. Listening for traffic...\n");
    printf("(Press Ctrl+C to exit)\n");

    // Keep the user-space program alive so the XDP hook remains attached
    printf("Monitoring traffic... Press Ctrl+C to stop.\n\n");

    // Get File Descriptors (FDs)
    int tracker_fd = bpf_map__fd(skel->maps.ip_tracker);
    int blocklist_fd = bpf_map__fd(skel->maps.blocklist);
    int allowlist_fd = bpf_map__fd(skel->maps.allowlist);
    int honeypot_fd = bpf_map__fd(skel->maps.honeypot_map);

    // --- INITIALIZE STORAGE DIRECTORY ---
    // 0755 means: Owner can read/write/execute. Others can read/execute.
    if (mkdir(IPS_SAVE_DIR, 0755) == 0) {
        printf("[i] Created new storage directory at %s\n", IPS_SAVE_DIR);
    }

    // --- LOAD SAVED DATA ---
    load_blocklist_from_csv(blocklist_fd);

    // --- SETUP RING BUFFER ---
    struct ring_buffer *rb = NULL;
    rb = ring_buffer__new(bpf_map__fd(skel->maps.ban_events), handle_ban_event, &blocklist_fd, NULL);
    if (!rb) {
        fprintf(stderr, "[!] Failed to create ring buffer\n");
        return 1;
    }

    printf("--- System Status: Event-Driven Mode Active ---\n");

    while (1) {
        // Wait for ban events from the kernel for up to 1 second
        // If an attack happens, this wakes up instantly (0ms latency).
        // If nothing happens, it loops every 1 second to run the aging logic.
        int err = ring_buffer__poll(rb, 1000);
        if (err < 0) {
            fprintf(stderr, "[!] Error polling ring buffer: %d\n", err);
            break;
        }

        bool blacklist_map_changed = 0;

        // ====================================================================
        // AGING (Blocklist Eviction)
        // ====================================================================

        // bl_key starts at prefixlen=32/ip=0 as a "doesn't exist" sentinel: the LPM_TRIE
        // falls back to the leftmost (first) entry when the given key isn't found, same as
        // a HASH map does for a key of 0. Deletions are collected and applied only after the
        // walk finishes, since deleting the pivot key mid-walk is fragile for LPM_TRIE.
        struct lpm_ip_key bl_key = { .prefixlen = 32, .ip = 0 }, bl_next_key;
        struct ips_blocklist_data bl_value;
        uint64_t current_time = (uint64_t)time(NULL);

        struct lpm_ip_key expired_keys[BATCH_SIZE];
        int expired_count = 0;

        while (bpf_map_get_next_key(blocklist_fd, &bl_key, &bl_next_key) == 0) {

            bpf_map_lookup_elem(blocklist_fd, &bl_next_key, &bl_value);

            // We ONLY age out dynamic bans (is_static == 0)
            if (bl_value.is_static == 0) {
                if (bl_value.ban_timestamp == 0) {
                    // meaning pending fixup with current time
                    // TODO: maybe an handling,
                    // although idk this is usually a breaking point only if the IPS is under attack, that's why i added an if to not unban a timestamp of 0
                }
                else if ((current_time - bl_value.ban_timestamp) > current_config.ban_duration_sec) {
                    if (expired_count < BATCH_SIZE) {
                        expired_keys[expired_count++] = bl_next_key;
                    }
                }
            }
            bl_key = bl_next_key;
        }

        for (int i = 0; i < expired_count; i++) {
            struct in_addr unban_ip;
            unban_ip.s_addr = expired_keys[i].ip;

            //Remove them from the eBPF blocklist.
            bpf_map_delete_elem(blocklist_fd, &expired_keys[i]);
            printf("[i] AGING: IP %s has served its time. Unbanned.\n", inet_ntoa(unban_ip));

            blacklist_map_changed = 1; //flag for change of map
        }

        if (blacklist_map_changed) {
            save_blocklist_to_csv(blocklist_fd);
            printf("[i] Blocklist saved to disk.\n");
        }
        
        // Dump the other maps for the monitoring TUI. Unlike the blocklist, these maps
        // (especially ip_tracker) can change on nearly every packet with no ring-buffer
        // event to key off of, so there's no cheap way to know "did it change" from
        // user-space. Just dump them every poll iteration instead -- the ring buffer poll
        // above already bounds this loop to ~1/sec when idle, same cadence as the aging check.
        save_tracker_to_csv(tracker_fd);
        save_simple_map_to_csv(allowlist_fd, ALLOWLIST_CSV_TEMP, ALLOWLIST_CSV_FILE);
        save_simple_map_to_csv(honeypot_fd, HONEYPOT_CSV_TEMP, HONEYPOT_CSV_FILE);
    }

    // Cleanup (This runs when you stop the program)
    ring_buffer__free(rb);
    bpf_link__destroy(link);
    ips_bpf__destroy(skel);
    return 0;
}

//
// Created by raul on 7/7/26.
//
