#include <stdio.h>
#include <unistd.h>
#include <net/if.h> // Required for if_nametoindex()
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include "ips.skel.h" // The skeleton header generated by bpftool
#include <arpa/inet.h>
#include <bpf/bpf.h>
#include <time.h>
#include <net/if.h>

#include "ips_fast_common.h"

int main(int argc, char **argv) {
    //Disable output buffering so printf shows up immediately in CLion
    setbuf(stdout, NULL);

    struct ips_bpf *skel;
    int err;

    // ----------------------------------------------------------------
    // AUTO-DETECT NETWORK INTERFACE & ATTACH
    // ----------------------------------------------------------------
    int ifindex = 0;
    const char *iface_name = NULL;

    // Try native Linux interface
    if ((ifindex = if_nametoindex("enp2s0")) > 0) {
        iface_name = "enp2s0";
    }
    // Try Oracle VM interface
    else if ((ifindex = if_nametoindex("enp0s3")) > 0) {
        iface_name = "enp0s3";
    }

    if (ifindex <= 0) {
        fprintf(stderr, "[!] Error: No known network interfaces found!\n");
        return 1;
    }

    printf("[i] Using interface %s (Index: %d)\n", iface_name, ifindex);

    // Attach the XDP program to the detected interface
    struct bpf_link *link = bpf_program__attach_xdp(skel->progs.fast_path_parser, ifindex);
    if (!link) {
        fprintf(stderr, "[!] Failed to attach XDP program to %s\n", iface_name);
        return 1;
    }

    // 2. Bump the memory limits. eBPF needs to lock memory in RAM.
    struct rlimit rlim = {
        .rlim_cur = 512UL << 20,
        .rlim_max = 512UL << 20,
    };
    setrlimit(RLIMIT_MEMLOCK, &rlim);

    // 3. Open and load the eBPF program into the kernel
    skel = ips_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    // 4. Attach the XDP program to your network interface
    // Note: "fast_path_parser" must exactly match the name of the C function in your ips.bpf.c file
    struct bpf_link *link = bpf_program__attach_xdp(skel->progs.fast_path_parser, ifindex);
    if (!link) {
        fprintf(stderr, "Failed to attach XDP program to %s\n", iface);
        ips_bpf__destroy(skel);
        return 1;
    }

    printf("IPS Fast-Path successfully attached to %s!\n", iface);
    printf("XDP is active. Listening for traffic...\n");
    printf("(Press Ctrl+C or use CLion's Stop button to exit)\n");

    // 5. Keep the user-space program alive so the XDP hook remains attached
    printf("IPS Fast-Path successfully attached to %s!\n", iface);
    printf("Monitoring traffic... Press Ctrl+C to stop.\n\n");

    //Get File Descriptors (FDs)
    int tracker_fd = bpf_map__fd(skel->maps.ip_tracker);
    int blocklist_fd = bpf_map__fd(skel->maps.blocklist);
    int allowlist_fd = bpf_map__fd(skel->maps.allowlist);
    int honeypot_fd = bpf_map__fd(skel->maps.honeypot_map);

    while (1) {
        sleep(1);

        __u32 key = 0, next_key;
        struct ips_token_bucket value;

        printf("--- System Status ---\n");


        // ====================================================================
        // LOOP 1: DETECTION (Token Bucket -> Blocklist)
        // ====================================================================

        // Loop through every entry currently saved in the Hash Map
        while (bpf_map_get_next_key(tracker_fd, &key, &next_key) == 0) {
            bpf_map_lookup_elem(tracker_fd, &next_key, &value);

            // Convert the 32-bit integer IP back into a readable string
            struct in_addr ip_addr;
            ip_addr.s_addr = next_key;

            // Print the current status
            printf("IP: %-15s | Tokens: %-3d | Drops: %-3d\n",
                   inet_ntoa(ip_addr), value.tokens, value.drop_count);

            //Auto-Ban Logic
            if (value.drop_count > MAX_TOLERATED_DROPS) {

                struct ips_blocklist_data block_data;
                block_data.ban_timestamp = (uint64_t)time(NULL); // Get current Unix Epoch time (seconds since 1970).
                block_data.is_static = 0; // Mark as a dynamic ban

                // Insert into the Blocklist Map
                bpf_map_update_elem(blocklist_fd, &next_key, &block_data, BPF_ANY);
                printf("[!] FLOOD DETECTED: %s banned! Drops: %d\n", inet_ntoa(ip_addr), value.drop_count);

                bpf_map_delete_elem(tracker_fd, &next_key);
            }

            // Graceful Reset
            // This forgives minor bursts over time and prevents false positives.
            else if (value.drop_count > 0) {
                value.drop_count = 0;
                bpf_map_update_elem(tracker_fd, &next_key, &value, BPF_EXIST);
            }

            key = next_key;
        }

        // ====================================================================
        // LOOP 2: AGING (Blocklist Eviction)
        // ====================================================================

        __u32 bl_key = 0, bl_next_key;
        struct ips_blocklist_data bl_value;
        uint64_t current_time = (uint64_t)time(NULL);

        while (bpf_map_get_next_key(blocklist_fd, &bl_key, &bl_next_key) == 0) {

            bpf_map_lookup_elem(blocklist_fd, &bl_next_key, &bl_value);

            // We ONLY age out dynamic bans (is_static == 0)
            if (bl_value.is_static == 0) {
                if ((current_time - bl_value.ban_timestamp) > AGING_THRESHOLD) {

                    struct in_addr unban_ip;
                    unban_ip.s_addr = bl_next_key;

                    //Remove them from the eBPF blocklist.
                    bpf_map_delete_elem(blocklist_fd, &bl_next_key);
                    printf("[i] AGING: IP %s has served its time. Unbanned.\n", inet_ntoa(unban_ip));
                }
            }
            bl_key = bl_next_key;
        }

        printf("------------------------------------\n\n");
    }

    // 6. Cleanup (This runs when you stop the program)

    bpf_link__destroy(link);
    ips_bpf__destroy(skel);
    return 0;
}

//
// Created by raul on 7/7/26.
//
